const mongoose  = require("mongoose");
const Schema = mongoose.Schema;
const listings = new Schema({
    email:{
        type:String,
        require:true
    },
    address:{
        type:String,
        require:true
    },
    bedroom:{
        type:Number,
        require:true
    },
    bathroom:{
        type:Number,
        require:true
    },
    phone:{
        type:String,
        require:true
    },
    zipcode:{
        type:Number,
        require:true
    },
    linkedin:{
        type:String,
        require:true
    },
    facebook:{
         type:String,
         require:true
    },
    website:{
        type:String,
        require:true
    },
    category:{
        type:String,
        require:true
    },
    listingTitle:{
        type:String,
        require:true
    },
    description:{
        type:String,
        require:true
    },
    image:{
        type:String,
        require:true
    },
    livingarea:{
        type:Number,
        require:true
    },
    price:{
        type:Number,
        require:true
    },
    previousprice:{
        type:Number,
        require:true
    },
    publishdate:{
        type:String,
        require:true
    },
    roadorstate:{
        type:String,
        require:true
    },
    cityorstate:{
        type:String,
        require:true
    },
    garageorparkingslot:{
        type:Number,
        require:true
    },
    yearinbuilt:{
        type:String,
        require:true
    },
    features:{
        type:Object,
        require:true
    },
    listingKeywords:{
        type:Object,
        require:true
    },
    tags:{
        type:Object,
        require:true
    },
    timeschedule:{
        type:Object,
        require:true
    }
})

const Listings = mongoose.model("listings",listings);

module.exports = {Listings}